const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  REDUCE_ITEM_QUANTITY_IN_CART: "REDUCE_ITEM_QUANTITY_IN_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART"
};
export default CartActionTypes;
